url: https://alliages.github.io
#baseurl: /

# Site settings
title: Paris change d'ère
email: paris2050@elioth.fr
description: "Rapport complet de l'étude Paris change d'ère, vers la neutralité carbone par Elioth Egis Conseil Quattrolibri Mana 2016"
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Elioth
  pic: 1
  position: mandataire du groupement, est une équipe multidisciplinaire composée d’ingénieurs, d’architectes, de designers et de datascentists, intervenant en R&D et en maîtrise d’œuvre d’innovation bas carbone, filiale du groupe Egis 
  social:
    - title: twitter
      url: https://twitter.com/elioth
    - title: linkedin
      url: https://fr.linkedin.com/company/elioth
    - title: link
      url: http://elioth.com

- name: Les équipes Conseil
  pic: 2
  position: d'Egis accompagnent les décideurs des territoires et de l’immobilier, depuis la structuration de leurs stratégies d’intervention, et jusqu’à la mise en œuvre effective de leurs projets 
  social:
    - title: twitter
      url: https://twitter.com/egis
    - title: link
      url: http://leconseilbyegis.fr

- name: Quattrolibri
  pic: 3
  position: société de conseil en stratégies bas carbone, qui intervient auprès de collectivités ou d’entreprises, et a mené des recherches sur les villes post carbone
  social:
    - title: twitter
      url: https://twitter.com/juliendossier
    - title: link
      url: http://www.quattrolibri.com

- name: Mana
  pic: 4
  position: bureau d’études et de conseil sociologiques spécialisé sur les questions relatives aux modes de vie, aux usages, aux imaginaires de la ville et des territoires
  social:
    - title: link
      url: http://www.manafactory.fr
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope-o
    url: mailto:paris2050@elioth
  - title: link
    url: http://elioth.com

# Postal address (add as many lines as necessary)
address:
  - line: 4 rue dolores Ibarruri
  - line: 93188 Montreuil

# Build settings
markdown: kramdown
permalink: pretty